#ifndef USB_DEVICE_ERROR_H
#define USB_DEVICE_ERROR_H

#define STATE_OK 0
#define NO_DLL 1
#define NO_FUNCTION 2
#define NO_DEVICE_CONNECTED 3
#define NOT_FULL_DATA 4
#define INVALID_PIPE_HANDLE 5
#define CALL_GET_LAST_ERROR 6
#define SESSION_ALREADY_OPEN 7
#define COMMUNICATION_ERROR 8
#define ASYNC_SESSION_RUNNING 9
#define NO_SESSION 10

#endif // USB_DEVICE_ERROR_H